// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgChnIaqTiI1WNj7SqMQyfYDoC1Ki8zvk',
    appId: '1:428056310385:web:810e22593355f86e4ca1d0',
    messagingSenderId: '428056310385',
    projectId: 'movie-app-c9935',
    authDomain: 'movie-app-c9935.firebaseapp.com',
    storageBucket: 'movie-app-c9935.appspot.com',
    measurementId: 'G-1BZ15FWDEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFW9eHFfvnZTI1QdVPjv-qqeS3sV6Url0',
    appId: '1:428056310385:android:dd672f8717fee9864ca1d0',
    messagingSenderId: '428056310385',
    projectId: 'movie-app-c9935',
    storageBucket: 'movie-app-c9935.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbDkX41_uc6pPWZiPmJ96C2cWUu1oqhus',
    appId: '1:428056310385:ios:f8801d204d41169a4ca1d0',
    messagingSenderId: '428056310385',
    projectId: 'movie-app-c9935',
    storageBucket: 'movie-app-c9935.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbDkX41_uc6pPWZiPmJ96C2cWUu1oqhus',
    appId: '1:428056310385:ios:041799bedb65e4154ca1d0',
    messagingSenderId: '428056310385',
    projectId: 'movie-app-c9935',
    storageBucket: 'movie-app-c9935.appspot.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
