// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_N1fhWJmQXd1GCZmrdqBcq25in6Dw1Vg',
    appId: '1:588007117450:web:076b2096d10ab6b71ed373',
    messagingSenderId: '588007117450',
    projectId: 'movie-app-dbce9',
    authDomain: 'movie-app-dbce9.firebaseapp.com',
    storageBucket: 'movie-app-dbce9.appspot.com',
    measurementId: 'G-8959MVXS87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApBPt6bsNhUgDKVRnwlqKhgWx95EW2A90',
    appId: '1:588007117450:android:fde438f9af3e51461ed373',
    messagingSenderId: '588007117450',
    projectId: 'movie-app-dbce9',
    storageBucket: 'movie-app-dbce9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWlqUKXOoXu3CqaQqXuIwzRoby7_OM0Ck',
    appId: '1:588007117450:ios:ab80bc99595f926d1ed373',
    messagingSenderId: '588007117450',
    projectId: 'movie-app-dbce9',
    storageBucket: 'movie-app-dbce9.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWlqUKXOoXu3CqaQqXuIwzRoby7_OM0Ck',
    appId: '1:588007117450:ios:ecccf90779b9b5c51ed373',
    messagingSenderId: '588007117450',
    projectId: 'movie-app-dbce9',
    storageBucket: 'movie-app-dbce9.appspot.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
